name: Run E2E Tests

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  e2e-tests:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository ğŸ“
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
  
      - name: Enable Corepack
        run: corepack enable || sudo corepack enable
    
      - name: Install deps
        run: yarn install
  
      - name: Set Up Starship Infrastructure
        id: starship-infra
        uses: cosmology-tech/starship-action@0.2.19
        with:
          values: starship.ci.yaml
          port-forward: true
          version: 0.2.2
          timeout: 25m

      - name: Run E2E Tests
        run: yarn test
